networks:
  ai-debater-net:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ai-debater-backend
    command: uvicorn backend.app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - ai-debater-net

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: ai-debater-frontend
    command: streamlit run frontend/app.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - BACKEND_URL=http://ai-debater-backend:8000
    depends_on:
      - backend
    networks:
      - ai-debater-net


